CREATE TABLE IF NOT EXISTS agent_trace_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_id VARCHAR(64) NOT NULL UNIQUE,
  request_id VARCHAR(128) NOT NULL,
  sequence_no INT NOT NULL,
  parent_event_id VARCHAR(64),
  dependency_event_ids JSON,
  round_index INT,
  event_type VARCHAR(64) NOT NULL,
  purpose VARCHAR(64),
  label VARCHAR(256),
  status VARCHAR(32) NOT NULL,
  project_id VARCHAR(128),
  project_name VARCHAR(256),
  tool_name VARCHAR(256),
  model_name VARCHAR(128),
  page_index INT,
  page_size INT,
  returned_count INT,
  reported_total_count INT,
  input_tokens INT NOT NULL DEFAULT 0,
  output_tokens INT NOT NULL DEFAULT 0,
  total_tokens INT NOT NULL DEFAULT 0,
  started_at TIMESTAMP(3) NOT NULL,
  finished_at TIMESTAMP(3) NULL,
  latency_ms BIGINT,
  input_json LONGTEXT,
  output_json LONGTEXT,
  usage_json LONGTEXT,
  error_json LONGTEXT,
  metadata_json LONGTEXT,
  INDEX idx_trace_event_request_sequence (request_id, sequence_no),
  INDEX idx_trace_event_request_event (request_id, event_id),
  INDEX idx_trace_event_started (started_at)
);

ALTER TABLE agent_audit_log
  ADD COLUMN trace_status VARCHAR(32) NULL AFTER error_message,
  ADD COLUMN trace_error_message TEXT NULL AFTER trace_status;
